name: 'Changelog checker'
description: 'Verify the changelog has been updated'
author: 'Zomzog@gmail.com'
branding:
  icon: 'bell'
  color: 'yellow'
inputs:
  fileName:
    description: 'Changelog fileName'
    default: 'CHANGELOG.adoc'
  noChangelogLabel:
    description: 'Label to ignore changelog check'
    default: 'no changelog'
  checksNotification:
    description: 'Simple or Detailed'
    default: 'Detailed'
runs:
  using: 'node12'
  main: 'dist/index.js'
