name: "build"
on: # rebuild any PRs and main branch changes
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all