name: "test"
on: # rebuild any PRs and main branch changes
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]

jobs:

  test: # make sure the action works on a clean machine without building
    if: ${{ github.action.payload.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}